# BUỔI 3: PHÂN TÍCH DỮ LIỆU VỚI PYTHON

In [2]:
!git clone https://github.com/wesm/pydata-book.git

fatal: destination path 'pydata-book' already exists and is not an empty directory.


# KẾT THÚC

In [ ]:
!rm -r pydata-book

rm: remove write-protected regular file 'pydata-book/.git/objects/pack/pack-f85b376896d3b59d9eef624c7f89ee142bf3b78c.idx'? 

In [ ]:
!ls pydata-book/
!sudo rm -r pydata-book.git

In [1]:
v = list(range(1, 6))
v
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
import numpy as np
v = np.arange(1, 6)
v


array([1, 2, 3, 4, 5])

In [3]:
2 * v

array([ 2,  4,  6,  8, 10])

In [5]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [6]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [7]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c


array([ 4, 10, 18])

In [8]:
import numpy as np

a = np.zeros((2,2)) # Create an array of all zeros
print(a)# Prints "[ [ 0. 0.]
        #[ 0. 0.]]"
b = np.ones((1,2))# Create an array of all ones
print(b)# Prints "[ [ 1. 1.]]"

c = np.full((2,2),7) #Create a constant array
print(c)# Prints "[ [ 7. 7.]

d =np.eye(2)# Create a 2x2 identity matrix
print(d)# Prints "[[ 1. 0.]
          #      [ 0. 1.]]"
e = np.random. random( (2,2)) # Create an array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.60769052 0.30284658]
 [0.97796552 0.04140218]]


In [10]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
print (a.shape)

(3, 5)


In [12]:
a.ndim

2

In [13]:
a.dtype.name

'int64'

In [16]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [17]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
a


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [20]:
b = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [23]:
print(b.shape)
print(b.ndim)


(3, 4)
2


In [24]:
a=np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(2, 2)


In [1]:
!git rm --cached BUOI3_2608/pydata-book/datasets/fec/P00000001-ALL.csv

fatal: pathspec 'BUOI3_2608/pydata-book/datasets/fec/P00000001-ALL.csv' did not match any files


In [4]:
!git commit -m "Remove large file from repo"


On branch main
Your branch is ahead of 'origin/main' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean


In [7]:
!pip install git-filter-repo
!git filter-repo --path BUOI3_2608/pydata-book/datasets/fec/P00000001-ALL.csv --invert-paths


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip
Aborting: Refusing to destructively overwrite repo history since
this does not look like a fresh clone.
  (GIT_DIR must be .git)
Please operate on a fresh clone instead.  If you want to proceed
anyway, use --force.


In [9]:
!git filter-repo --path BUOI3_2608/pydata-book/datasets/fec/P00000001-ALL.csv --invert-paths --force

NOTICE: Removing 'origin' remote; see 'Why is my origin removed?'
        in the manual if you want to push back there.
        (was https://github.com/phamngan828am/ueh25.ktltpythonvastata)
Parsed 28 commits
New history written in 0.06 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
HEAD is now at 9678282 xóa file lớn
Enumerating objects: 303, done.
Counting objects: 100% (303/303), done.
Delta compression using up to 2 threads
Compressing objects: 100% (289/289), done.
Writing objects: 100% (303/303), done.
Total 303 (delta 49), reused 2 (delta 1), pack-reused 0 (from 0)
Completely finished after 7.43 seconds.


In [12]:
!git add
!git commit -m "Remove large CSV file from repo history"

Nothing specified, nothing added.
hint: Maybe you wanted to say 'git add .'?
hint: Disable this message with "git config set advice.addEmptyPathspec false"
On branch main
nothing to commit, working tree clean


In [13]:
!git branch -M main
!git remote add origin https://github.com/phamngan828am/ueh25.ktltpythonvastata.git
!git push -u origin main --force

Enumerating objects: 307, done.
Counting objects: 100% (307/307), done.
Delta compression using up to 2 threads
Compressing objects: 100% (245/245), done.
Writing objects: 100% (307/307), 39.97 MiB | 13.09 MiB/s, done.
Total 307 (delta 52), reused 301 (delta 49), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (52/52), done.
To https://github.com/phamngan828am/ueh25.ktltpythonvastata.git
 + cc62e94...95bb4b8 main -> main (forced update)
branch 'main' set up to track 'origin/main'.
